## तिर नजरका

कर्के नजरका तिरहरू चलाउँछ्यौ तिमी    
छाती थाप्न सयौँ युवकहरू तौनाथ छन् ।    

आँखा तिम्रा कविता बोलिरहेछन् बोली चाँहि युद्ध   
तिम्रो मनसाय अर्थयाउन धड्कनहरू हैरान छन् ।   

सूर्यलाई अंगालोले बेर्दा भष्म बनाउला भन्ने डरमा       
तिम्रा सूर्यमूखी फूलहरू जून पुज्न विवश छन् ।   

जानेलाई जान दिउ भन्छ एक त्याँगी ठिटो    
तिम्रो नाम जप्ने बैरागीहरू हजार छन् ।   

पाउँजु जस्तै तिम्रा पाउँ पनि समयका उपहार न हुन्    
पहिले छाती सजाउने फूलबारीहरू अहिले उजाड छन् ।   

हँसाऊ भो तिम्रो मुहार रुनलाई त मन लुकेरै रोइहाल्छ   
यो चक्र यस्तै छ प्रिय यहाँ फूल भमरा दुबै उदाश छन् ।

## तबाह
यूं ही खुद से खुदा बन गए हम सनम    
तुमसे जुदा हो न सके मगर ।   
खुदा होकर हमने सिर्फ आपको नहीं   
तुम्हें भी तबाह कर दिया है । 

## Notes from Underground

All my dreams have died--   
A death of strayed dogs--    
Unattended, Under-nourished.

They have died thousand deaths indeed--   
Neither did I console them at their final moments--    
How cruel, insolent, and evil, you may think.   

Think, please do, be my uninvited guest--    
I thought of how I inherited them plenty--    
Never did I find an answer singular and straight.   

A man in moments? A moment of a man? A man of a moment?    
What am I, eh? A gift, a cause or just another uncalled accident?        
Despite confusions, I've got funny ideas. Can I laugh at a funeral?

## A Sketch

a thought in a collective brain--    
an atom in the cosmic sphere--    
a day in the years of the universe--    
just a sight for most--   
a heart's delight for few--   
i know you, don't i ?   

a face, a name, an idea--   
a metaphor, a narrative--   
a comical tragedy indeed--    
a beginning of the end--   
a random play, a staged drama--      
i know you, don't i?    

a drop in the ocean or from the sky--     
a drop that might boil or freeze--   
a leaf of the spring--    
a leaf yet to find its hole in the ground--   
or its wings to take a flight?       
i know you, don't i?   

# just a drop you can't count

all has been seen and said before––       
the barred faces, caged wings,
the falling clouds, sheer cliffs,
and the statues singing in graves.

yet each step as it begins quivers      
while the road chants its names 
though seen a thousands times before
each time a heart breaks, it differs.

a map, a compass, a committee, all prepared
when dirt fills the gaze and stills the mind
we will still have plans for days ahead
with all unseen tears left behind, we depart.

## एक कुवाँ
meh meh   
आफै भित्र कतै एक कुवाँ सङ्लिएको छ सायद    
त्यहाँ छप्ल्याक्-छप्ल्याक् गर्ने मान्छे मै हुँ सायद ।      

कुवाँमा जाल थाप्ने माँझीहरू पनि कवाँमै कैद हुन्छन् सायद    
हप्ताका दुई-चार बार यिनै माछा-माँझीहरू गफ्फिन्छन् सायद ।      

ऐनामा एक माछा पौडेको देखिन्छ अनि भित्र अर्कै पौडिरहेछ सायद    
बाहिर बाहिर एक शरिर कुवाँ र माछा दुबै बोकेर दौडिरहेछ सायद ।       

के कविता लेख्दो हो कवि, बिम्बै बिम्बमा भाँसिएर माँसिने भो सायद   
अर्थ दर्शाउन जन्मेको एक वाक्य हिलोमा लत्पत्तिएर निसासिने भो सायद ।       

खैर, कठैबरा कवि यै टुकुचे कुवाँमा उदाएको सूर्य त लेख्दो हो सायद   
जति कुवाँ छन् यहाँ त्यति नै भिन्न-भिन्न सूर्यको उदय देख्दो हो सायद । 

## A Coin Toss

A borken ankle,    
A broken toe,    
A broken arm--twice.    

All these bones--   
Summoning the devil in this body.   

Poor heart, now is your time--   
You should take a chance.  

## ए मेरे अच्छे चांद
ये मेरा चाँद कुछ कहता क्यों नहीं?   
ख़ामख़्वाह ख़ामोशी में चुपचाप डूबा रहता है क्यों?   

क्या सोच रहा है? क्या भूल गया है?   
दिल की हर बात छुपाना ज़रूरी है क्या?  

## च्याट

तिम्रो नाममा फेस्बुकमा एउटा टाट पल्टेको च्याट बाँकी छ      
तिम्रो व्यवास्ताले कुँजिएको वार्तालापलाई कसरी उभ्याऊँ कुन्नी ?       

कुराकानीमा खास्सै बिग्रे-झुक्केकै होस् भन्ने पनि त केहि छैन        
तिमी हाँस्दा हाँस्दै रिसायौ सधैँका लागि भनी कसरी मानूँ कुन्नी ?       

कुराको बिट् मार्न तिमीले केही ठेला-टुप्पाका कारणहरू जरुर भनेकी हौ      
धेरै बयानहरूको सत्य एक-दुई कोस टाढा हुन्छ भन्ने कसरी नकार्नु कुन्नी ?     

तिम्रा औलाहरू अरू कसैको तारिफमा फुर्र-फुर्र नाँच्दै होलान्            
औलाहरू झुक्केर कहिल्यै हाम्रै च्याटमा नफर्केलान् भनी कसरी सोचूँ कुन्नी ?    

यसो पनि होइन कि सबै खोलाहरू समुद्रमा नै मिस्सिनु पर्छ           
तर तिम्रो भाग्य क्यौँ मुहानहरूको हातमा थमाई आँफू बग्न कसरी छोडूँ कुन्नी ?      

## सोचे-सोचे

जुग-जुग पहिले नै सोचे-सोचे लाग्ने एउटा सोच भिटियो    
एक सोचमा लठ्ठी प्रहार गर्ने अर्को सोचको आँट भेटियो ।      

अन्तमा सिंगो ओखतीको आसमा धेरै चोटपटक सहियो   
एक तिर टाल्दा छानो अर्को तिर चुहिँदा भरसक सहियो ।        

बुझ्नु कसरी रोग हो कि ओखती हो जो पहिले पलायो   
जिन्दगी चढ्दा जरा देखि हाँगासम्म सोच कहिले पलायो ?      

पहिलो सोच कुन अन्तिम चाहिँ कुन हो भन्ने कस्ले टुङ्ग्यायो ?        
गल्लीमा उत्तर बाड्दै हिँडेका दैबको पहिचान बहसले टुङ्ग्यायो ।        

देखे-देखे लाग्ने धुलाम्मे तस्बिरमा एक मधुरो मुहार देखियो   
आत्मा बिलाई गयो आखिरी कोखमै वायूमा आकार देखियो ।        


## आवत-जावत

जानेहरू ढोका बन्द गरेर जान्छन्    
आउनेहरू दैलोबाटै फर्केर जान्छन् ।     

कोही आउनेहरू ढोका ढक्ढक्याउन पनि    
यो चरम बेहोसीको मन बिउझाउँन हुन्थ्यो ।    

हुन त जानेहरूले दुनियाँसँग बिछोडिन सिकाएर जाँदा       
नआउनेहरूले बन्द कोठाबाट आफै निस्कन सिकाउछन् ।   

यि जानेहरू, यि आउनेहरू, अनि यि नआउनेहरू सबैले    
म पनि त यहीँ नगरको अस्थायी घुमन्ते हुँ भनेर सम्झाउछन् । 

## बद्ला    

बदलामा बाँच्छ ऊ, भन्छ––      
उस्को भन्दा दोब्बर कमाउँछु   
टोलकै सान्दार भवन बनाउँछु   
नाममा नमस्कार गर्ने बोली जुटाउँछु         
आफू बाहेक सबको बदनाम फैलाउँछु ।    

बदलामा बाँधिएर   
बदलामै बादल भएर    
बदलामा नबद्लिएर   
बदलामै गुमनाम हुन्छ ऊ ।  

## बराबर

फूपुले गहुँ-मकै पिध्ने बेसीको त्यो जिर्ण पानी घट्ट    
सभ्यताको लामो दौड् बिनानै ठडिएको होला त झट्ट ?   

भित्ताको बाह्रैमास हाँसिरहने गजक्क परेको तस्बिर    
ल्याएर आएको होला त कहिल्यै नबिझाउने तक्दिर ?   

हिजोको लाठीचार्ज भोलीको फाँसीमा कैद बर्तमान    
नबिउझाएरै रातको सपनीबाट फुत्केला त हर बिहान ?    

पाएको सापटी एउटै जीवन जगतको गर्भबाट    
बिना कर्म अँजुलीमा अर्थ भेटिएला त निर्धक्क ?    

ब्याङ्ग्य गरिरहेछ नदी किनारबाट एक आर्यघाट   
माटो-मुस्लोमा समान नहोला त सबको औकात ? 

## यस्त-यस्तै छ

पर कतै भट्टीमा एक जडियाँ   
एक दुई बोतलको घुट्कीमा   
घाँटीमा अड्केको सत्य निल्दै छ ।       

पुस्तकालयको भित्री कुनामा एक सिपाही    
एक दुई हरफको अङ्गालोमा    
छातीमा गँडिएको गोली खियाउँदै छ ।    

संगित गुञ्जिरहेछ    
चियाँ पसलमा ज्यानहरू बिसाउन पाएकै छन्   
कहिलेकाहीँ गोजी छाम्दै फोनकलहरू आइपुग्छन् ।  

## एक किलो दिलमा

दशैमा भित्ताले    
नयाँ रङ्ग पाएजस्तो    
अस्तित्वको रङ्ग फेर्न पाए ?   

खोलाले बोकेका थोपाजस्तै   
पहिचानका डोकाहरू    
बाफहरूलाई सूम्पिन पाए ?    

आज पनि सयौँ हिजो पनि उत्तिकै धेरै    
भोली पनि पेट भरी बाँची सकियो    
दुई स्वासमै समयको निष्कर्ष निचोड्न पाए ?    

सम्झनाको मैदानमा एक परीका लात्तीहरू   
भकुण्डो खेलीरहेछन धेरै वर्ष पूर्व देखि   
उस्लाई बाँध्न दिलमा एक किलो ठोक्न पाए ?   

सपना बिर्सेर मुन्टो माटोमा गाँडिहाल्न पनि नसकिने           
सुर्जेको शिरमा गोडा ढोगाउदै गर्दा           
इकारसलाई गगन मूनिको खाडल दर्शाउन पाए ? 

## परिचय    
को हुन् उनी जो हाँसेर गइन् हिमालको हाँसो––      
मिलेको जिउडालमा जो नाचेर गइन् मयूरको नाच ?   

को हुन् जस्ले चेतनामा कोरेर गइन् भविष्यको सुनौलो तस्बिर––           
कर्के नजरले नै जो उद्दार गरेर गइन् कुहिरोमा अलपत्र तक्दिर ?       

को हुन् उनी जस्को हाउभाउले नै कोर्छ उत्कृष्ट कविता––          
अनुपस्थितिले जस्को एकलकाटे मनमा उब्जाउँछ द्विविधा ?        

को हुन् जस्ले लुकाइनन् खाल्टोको पानीबाट आफ्नो चन्द्रमुख––          
डेढोलो लागेको दिनहरूमा सितलता फैलाउने एक कृपालु रूख ?      

को हुन् उनी जस्ले हाँसेर भाँचिन एकलवासको दिलको ताल्चा––          
दुई भिन्नै फूल एउटै बारिमा हुुर्किदा नमासिने गरिन जस्ले बाँचा ? 


## बर्बादी

म पढे-लेखेको लक्का जवान    
तिम्रो निधारमै प्रष्ट लेखिएको    
मेरो नाम चिन्दिन होला त ?   

चियाँको कपबाट बाँफहरू उडेजस्तै   
बैसको तरङ्गहरू उड्दा ज्यानबाट    
तिमीसँग यथार्थको चियाँ पिँउदिन होला त ?   

तिमीलाई मन पर्ने अर्को झिल्के   
अरु कसैको मायामा विलिप्त भएको   
सुचना सरासर गलत होला त ?   

कवि ज्यूँका हरफहरूका माला भिर्दै    
मानौली आफू सुर्य अनि ऊ सुर्यमुखी         
ऊ तिम्रो सारा अस्तित्व सुम्सुम्याउने बर्षात होला त ?    

बेँसीका पैतलाहरू सगरमाथा पुगेकाछन्   
आज वास्तै गरिनौ भोली आँखा तरौली    
पर्सी मायाको टुसो पलाउन असम्भब होला त ?    

आँखाले चस्मा खुट्टाले लट्ठी पाएकै छन्   
आखिरीमा तिम्रो गन्तब्य अर्कै अंगालो ढोग्न जाँदा      
घाइते यो दिल मलम नपाएरै बर्बाद होला त ?   


## व्यस्त सहरको प्रेमी

सुन्छु तिमीलाई––        
दिनमा रात रातमा दिन प्यारो लाग्छ ?    
जून उज्यालो अनि सूर्य अध्याँरो लाग्छ ?   
यसरी तिम्रो हकिकत पल्टाउने निष्ठुरी को हो साथी ?    

सुन्छु तिमीलाई––        
हिजो आजको भन्दा भोलीको आश बर्ता लाग्छ ?   
बाटो हिँड्ने हर मानिसको दिल एक हतियार लाग्छ ?   
यो दर्दनाक कहानीको अचानो को खुकुरी को हो साथी ?   

सुन्छु तिमीलाई‍‍––      
आदर्शबादीहरू घटियाँ र बैरागीहरू सत्य लाग्छ ?   
दिलको वर्षामा ओत दिने घुट्की सभ्य लाग्छ ?  
यो व्यस्त सहरको फूर्सदिलो प्रेमी को हौ साथी ?    

## के हो ?

खिस्स हाँस्ने दिल चोर्ने––        
भन तिम्रो लक्ष्य के हो ?   

दर्जन दिलमा कम्पन ल्याउने    
भन तिम्रो सत्य के हो ?    

एक तिर दुई सिकार    
भन तिम्रो कटाक्ष के हो ?   

मन, तन, जीवन नै धितो राख्दिन्छु    
भन तिम्रो परीक्षा के हो ?    

झुट्मा डुबाउने कि यथार्थले जोगाउने   
भन तिम्रो कर्तब्य के हो ?    

सिमाना कति नाघ्ने बन्धन् कति तोड्ने    
भन तिम्रो सभ्य-असभ्य के हो ?  

## परिस्थिति 

बोलीमा नखोलिएका मन्थन आँखाले सुनाउँछन्    
गाउँमा नसुनिने कष्ठहरू वन पाखाले सुनाउँछन् ।   

गुलाबले दर्शाउन नसक्ने माया धड्कनले चिनाउँछन्    
रगतले गाँस्न नसकेको सम्बन्ध अड्चनले चिनाउँछन् ।   

पूर्ण जीवनको अपुरो हिसाब त्यागले सम्झाउँछन्    
झिना-मसिना उमङ्गको मूल्य सन्तापले सम्झाउँछन् ।   

समय र स्थानको पर्खाल नाघ्न नदी खोलाले सिकाउँछन्     
पर्वत चढ्न पहिरो छल्न निष्कपट हौसलाले सिकाउँछन् ।   

भव्य जीवन साधारण दिनचर्या मनस्थितिले जनाउँछन्     
एक मान्छे असल कि बेइमान परिस्थितिले जनाउँछन् । 

## बन्धन्

धुलाम्मे सहरमा    
कोलाहल यादहरूमा    
मधुरा सपनामा    
तिम्रो चित्र प्रष्ट नाचिरहन्छ ।   

सूर्यको उडान-डुबानमा   
कछुवा-खरायोको गतिमा    
शिशिर वसन्तमा   
मन तिम्रै नाम गुन्गुनाउँछ ।    

माया तिम्रै सर्वोच्च    
चोट पनि तिम्रै उत्कृष्ट   
केही आउला अनि रोप्ला   
तिम्रा भन्दा भब्य फूल-काँडाहरू      
भन्ने सोचैम मन झस्किरहन्छ ।   

## चिठ्ठी

हो, हरेक झरनाले साँगर भेटाउदैनन्   
अनि सारा थोपाहरू बादल बन्दैनन्    
चिठ्ठीका आठ-दश वाक्यमा   
म पोखिएको हुँ    
तिमी भिज्नु पर्छ भन्ने पनि जरुरी त छैन ।   

आस्थाको मधुरो दियोले दैब जन्माइदिन्छ   
भोलीको प्रतिक्षाले आज बिर्साइदिन्छ  
तिम्रो मुस्कानको भाव तन्काएर     
मैले प्रेम सेवन गरेको हुँ    
एकोहोरो मायाको बाटो त भ्रमले नै खनिदिन्छ ।    

बुद्धीले नापेर प्रेम गरूँ भने    
सुरुमा भग्वानलाई खेद्नु पर्छ    
अनि तम्तयार हुनु पर्छ   
मायाका चोटिला डामहरू सहन र        
जलपरी जस्तीलाई किच्कन्या भन्न ।    

बरु ठिकै छ यसरी नै   
चिठ्ठी लेख्छु शब्दकोश रित्त्याएर   
आशाका किरणले ज्योती बाल्छु    
उजेली रातको यि नक्षत्रमा    
तिम्रा मुहारका बुट्टाहरू भरी बस्छु ।  

## हतेलीहरू

चोयाका त्यान्द्राहरू   
मिलाएर डोको बुन्ने   
ति बाजेका औलाहरू    
देवकोटाका औला जस्तै    
सिर्जनशील लाग्छन् ।    

पिठ्यूमा एक पुलो खर   
गाई गोठ तिर डोऱ्याइरहेकी        
ति आमैका पैतलाहरू पनि    
पासाङ ल्हामुका पैतलाझैँ
गगन-चुम्बी लाग्छन् ।    

समाजले आहा र स्याबास भन्न    
भुलेका, नसक्ने, या नचहाने      
दिनहुँका सुस्केरहारू   
सम्पूर्ण किर्तिमाणहरू जत्तिकै    
भब्य र सहासी लाग्छन् । 

## गुनासो

ऐनामा दिनहुँ देखिरहेको एक दृश्य पनि बद्लेछ   
हामी बिचको नाताको आजकाल परिचय बद्लेछ ।   

ढाँडको हाँड सोज्याउन नपाउदै आज रात ढलेछ   
सारा जँघार साथै तर्ने बाचाको अदालत ढलेछ ।    

एक दुई दिनको भेटघाटलाई अनयासै सदाबहार सम्झेछ    
माया दिने मनले माया पाउनु नै पर्ने अधिकार सम्झेछ ।    

ढकमक्क फूलहरू झरेर जाँदा रूख त नाङ्गै भएछ    
फर्किने बाटो नसोधी जाँदा तिमी मन खक्रकै भएछ ।   

वसन्तले पुन: बाँसी बस्तीमा मगमगाउने बतास ल्याएछ   
आफै भित्र घाँउ र उपचार दुबै भएको सन्देश ल्याएछ ।   

संसारिक तालमेल नमिली ठक्कर खाँदा बैरागको टुसो जागेछ      
चमक मात्र हेरी आउने दाग खोजेर जाने प्रति गुनासो जागेछ ।    

## रुञ्चे

आँशु सँगालिएकै छन् महिनौ देखि एक बटुल्ने अंगालो पर्खेर   
टाँठाबाँठाले सताइएको एक दिल बसेको छ एक दयालु पर्खेर ।      

चन्द्र तारा निदाएको एक रात बिताउला बतासका गित सुनेर    
चियाँउला तिम्रा मेरा यात्राहरू स्मृतिमा कैद हारजित सुनेर ।       

अतितको भोटो छोटो-मैलो हुँदैजाँदा उपहार दिउँला अर्को बुनेर   
कुसुमे रूमालले के तेग्थ्यो जाँडो बरै ओढौला सँगै बर्को बुनेर ।    

बोलीमा समेट्न नसक्दा भोगाइ हामी अल्झी बसौँला मौन्ता बुझेर    
जन्मिनु कि मर्नु अन्याय फैसाला पनि साथै गरौँला अवस्था बुझेर ।   

सोच कति लामा-चाख्ला सकिन्छ कि सारा समय कसैलाई कुरेर    
केही हुन हिँडेको अनुहार वर्षौ बिताइसकेछ ऐनामा आफैलाई कुरेर ।   

## मगन्ते

कुनैबेला सृङ्गारको भोकमा मैले जुन माँगे   
कैले चाहिँ मैले सम्पत्तिको आसमा सुन माँगे ।      

जवानीको उन्मादमा कसैसँग साइनो गाँसिदिन भनेँ  
घुम्ति पिच्छे काम, नाम, र इनामको याचना गरेँ ।     

ब्रह्माण्ड सोच्दो हो म एक नअघाउने मगन्ते        
तर यो शाश्वत भोकको आफ्नै इंजन छैन र ?        

मेरा मागहरू जस्तै   
मलाई माग्नेहरुको पनि लस्कर छ––            
समाजको र परिवार केहि अपेक्षा छ––              
जन्मिनु आफैमा एक पौराणिक ऋण न हो––      
पुर्खाले भेटि खोज्छन् भावी पिढी अंश––            
आफूभित्रको एक अन्जानले पनि त सुबिधा माग्छ ।  

## ओहोर-दोहोर

यो बाटोमा पहिले पनि हिडेको हो    
यो यात्री पहिले पनि ढलेको हो ।     

अन्जान मुहारसँग पहिले पनि जोडिएको हो     
प्राणप्रिय साइनो पहिले पनि तोडिएको हो ।     

आशा भरोसाका धुनमा छम्छमी पहिले पनि नाचेको हो    
रोगी वर्तमानको दोषी इतिहास पहिले पनि जाँचेको हो ।     

जीवनले हरेक बाधा जित्दा मृत्यूले पहिले पनि हारेको हो    
कच्कचे समाजको पहिरो मौन्ताले पहिले पनि टारेको हो ।   

## भाथ्यो कि ?
शव्दहरू उस्तै कथाहरू बर्बराइरहन्थे    
जीवनको पाना पल्टाउने बेला भाथ्यो कि ?   

नयाँ गाउँको नक्सा कोरेकाहरू चल्मलाइरहन्थे    
सम्बन्धको खिड्की उघार्ने बेला भाथ्यो कि ?   

छिमेकीहरू तिलको भरमा पाहाड ठड्याइरहन्थे    
सन्चो-विस्नचोको जबाफ मुस्कानले टार्ने बेला भाथ्यो कि ?   

सम्झना र सपनाहरू अक्सर झम्टिरहन्थे    
सोचहरू रित्तिन दिएर शून्यता अंगाल्ने बेला भाथ्यो कि ?    

पाइलाहरू उकालो सम्झेरै कठ्याङ्ग्रि रहन्थे       
चढेको उकालो अवलोक्न गर्दै चौतारीमा सुस्ताउने बेला भाथ्यो कि?

## अर्थतन्त्र     
तिमी मलाई जति माया गर्छेउ       
म पनि गर्छु कसैलाई त्यति नै ।   

तिमीलाई लाग्दो हो    
म मायाको अर्थ बुझ्दिनँ ।    

अर्थ मायाको सिकेर आएकै हौँ सब   
आमाको गर्भबाट जो मभित्र पनि   
डेरा जमाई बसेको छ केही जन्म देखि ।    

यद्यपी मैले सकेको छुइन अझै पनि      
प्रेमको गञ्जागोल अर्थतन्त्र मिलाउन ।    

यहाँ म लत्पत्तिएको छु यसरी  
जसरी तिमी दलदलमा परेकी छौ        
आशा र यथार्थको द्वन्द चलिरहदा छाती भित्र           
एक हात दानी अर्को चाँहि भिक्षु भएको छ । 

## सिलाई-कटाई

घुम्ती जीवनका सारै थकाउने    
मन भने पोल गाड्दै छ––        
पिङ अझैँ खेल्ने अरे ।   

माया मोहले भष्म नै बनाउने   
मन भने आगो जोड्दै छ‍––      
आफू अझैँ जल्ने अरे ।   

नुन-सुन-बैगुन सबै ढाँड सेकाउने    
मन भने गोजी बुन्दै छ––       
खोक्रोपना अझैँ बटुल्ने अरे । 

## अन्याय

तिमी कसैको अङ्गालोमा हुनु यो भविष्यलाई अन्याय भो   
तिमी विशाल समुद्रसम्म पुग्नु यो पोखरीलाई अन्याय भो ।      

तिमी कसैको प्राकाश हुनु यो ग्रहणलाई अन्याय भो    
तिम्रा हत्केलाले चन्द्रा छुनु यो काँधलाई अन्याय भो ।    

तिम्रो कविता सधैँ बाँचिरहनु यो कलमलाई अन्याय भो     
तिमी विगतमा मात्र भेट्टिनु यी कदमलाई अन्याय भो ।   

तिम्रो सिउँदो उसँग मुस्कुराउनु यो रगतलाई अन्याय भो   
तिमी बेहोसीमा मात्र भेटिनु यो वर्तमानलाई अन्याय भो ।        

तिमी आकाश धर्तीमा फूल्नु यि काँडालाई अन्याय भो   
तिमी बेर अबेर झुल्किरहनु यो अन्धोलाई अन्याय भो ।   